# Generated by Django 5.1.1 on 2024-10-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysearchproapp', '0003_alter_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
    ]
